name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Generate Go code
        run: go generate ./...

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o autocommitai .

      - name: Create Linux tarball
        run: tar czvf linux-amd64.tar.gz autocommitai

      - name: Delete Linux binary
        run: rm autocommitai

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o autocommitai.exe .

      - name: Create Windows tarball
        run: tar czvf windows-amd64.tar.gz autocommitai.exe

      - name: Delete Windows binary
        run: rm autocommitai.exe

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o autocommitai .

      - name: Create macOS tarball
        run: tar czvf darwin-amd64.tar.gz autocommitai

      - name: Delete macOS binary
        run: rm autocommitai

      - name: Archive artifacts
        run: tar -czvf autocommitai.tar.gz *.tar.gz

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: autocommitai
          path: autocommitai.tar.gz
