name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o autocommitai-linux-amd64 .

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o autocommitai-windows-amd64.exe .

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o autocommitai-darwin-amd64 .

      - name: Archive artifacts
        run: tar -czvf autocommitai-$GITHUB_SHA.tar.gz autocommitai-*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: autocommitai-$GITHUB_SHA
          path: autocommitai-*.tar.gz
